### ISSUE TITLE
Push reports to SafeCity backend

### ISSUE THREAD

**Issue by carolineh101** [ashi-agrawal/SafeCity-Android#6]
- [x] Push report to backend JSON

**Comment by ashi-agrawal** [comment]
@carolineh101 It seems we might be able to push creation of reports after an API call to 2.0 since there's no immediate need for it with the reporting flow. We might want to focus energies on figuring out how to collect and continually update the number of reports and  find hotspots so we can create the hotspot map. Thoughts?

**Comment by ashi-agrawal** [comment]
Closing this and moving pulling reports from the backend to a separate issue so it can be assigned to a different milestone.
